
.PHONY:

NPM=npm
BOWER=node_modules/.bin/bower
BOWER_INST=node_modules/.bin/bower-installer

all:

vendor-install:
	$(NPM) install
	$(BOWER_INST)

vendor-update:
	$(BOWER_INST) update

docs-preview:

docs:
